trainingInput:
  scaleTier: STANDARD_1
  runtimeVersion: "1.13"
  # Note that both Python 2.7 and Python 3.5 are supported, but Python 3.5 is the
  # recommended one since 2.7 is deprecated soon
  pythonVersion: "3.5"
