jobs:
- stepId: 'SparkPi'
  sparkJob:
    args:
    - '1000'
    jarFileUris:
    - 'file:///usr/lib/spark/examples/jars/spark-examples.jar'
    mainClass: 'org.apache.spark.examples.SparkPi'
- stepId: 'MapReducePi'
  hadoopJob:
    args:
    - 'pi'
    - '16'
    - '1000'
    mainJarFileUri: 'file:///usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples-2.9.2.jar'
  prerequisiteStepIds:
  - 'SparkPi'
placement:
  managedCluster:
    clusterName: 'ephemeral-cluster1'
    config:
      gceClusterConfig:
        internalIpOnly: true
        zoneUri: ZONE 
        subnetworkUri: https://www.googleapis.com/compute/v1/projects/PROJECT/regions/REGION/subnetworks/SUBNET
        tags:
        - hadoop-admin-ui-access
        metadata:
          enable-oslogin: "TRUE"
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 500
          bootDiskType: pd-standard
        machineTypeUri: n1-standard-2
        minCpuPlatform: AUTOMATIC
        numInstances: 1
      softwareConfig:
        imageVersion: preview
        properties:
          yarn:yarn.log-aggregation-enable: "true"
          yarn:yarn.nodemanager.remote-app-log-dir: gs://HISTORY_BUCKET/yarn/logs/
          yarn:yarn.log-aggregation.retain-seconds: "604800"
          yarn:yarn.log.server.url: http://HISTORY_SERVER-m:19888/jobhistory/logs
          mapred:mapreduce.jobhistory.address: HISTORY_SERVER-m:10020
          mapred:mapreduce.jobhistory.webapp.address: HISTORY_SERVER-m:19888
          mapred:mapreduce.jobhistory.done-dir: gs://HISTORY_BUCKET/done-dir/
          mapred:mapreduce.jobhistory.intermediate-done-dir: gs://HISTORY_BUCKET/intermediate-done-dir/
          spark:spark.eventLog.dir: gs://HISTORY_BUCKET/spark-events
          spark:spark.history.fs.logDirectory: gs://HISTORY_BUCKET/spark-events
          spark:spark.ui.filters: org.apache.spark.deploy.yarn.YarnProxyRedirectFilter
          spark:spark.yarn.historyServer.address: HISTORY_SERVER-m:18080
      initializationActions:
        - executableFile: gs://HISTORY_BUCKET/init_actions/disable_history_servers.sh
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 500
          bootDiskType: pd-standard
        machineTypeUri: n1-standard-2
        minCpuPlatform: AUTOMATIC
        numInstances: 2
