trainingInput:
    scaleTier: STANDARD_1
    hyperparameters:
        goal: MAXIMIZE
        hyperparameterMetricTag: accuracy_per_class #can also use accuracy
        enableTrialEarlyStopping: True
        maxTrials: 30
        maxParallelTrials: 6
        params:
        - parameterName: train-batch-size
            type: INTEGER
            minValue: 8
            maxValue: 128
            scaleType: UNIT_LINEAR_SCALE
        - parameterName: first-layer-size
            type: INTEGER
            minValue: 30
            maxValue: 300
            scaleType: UNIT_LINEAR_SCALE
        - parameterName: num-layers
            type: DISCRETE
            discreteValues:
            - 2
            - 3
            - 4
            - 5
            scaleType: UNIT_LINEAR_SCALE
        - parameterName: layer-sizes-scale-factor
            type: DOUBLE
            minValue: 0.2
            maxValue: 0.8
            scaleType: UNIT_LINEAR_SCALE
        - parameterName: threshold
            type: DOUBLE
            minValue: 0.1
            maxValue: 0.9
            scaleType: UNIT_LINEAR_SCALE
        - parameterName: learning-rate
            type: DOUBLE
            minValue: 0.0001
            maxValue: 0.5
            scaleType: UNIT_LINEAR_SCALE
            