version: google.com/cloud/pipelines/component/v1
name: Train git cmle model
inputs:
- {name: tr_inp, type: str}
- {name: va_inp, type: str}
- {name: code_repo, type: str}
- {name: code_folder, type: str}
- {name: project, type: str}
- {name: bucket, type: str}
- {name: package_folder, type: str}
- {name: cmle_folder, type: str}
- {name: scale_tier, type: str}
- {name: python_module, type: str}
- {name: region, type: str}
- {name: runtime_version, type: str}
- {name: cmle_args, type: str}
outputs:
- {name: output}
implementation:
  container:
    image: gcr.io/energy-forecasting/component-train-git-cmle-model:latest
    args:
    - {value: tr_inp}
    - {value: va_inp}
    - {value: code_repo}
    - {value: code_folder}
    - {value: project}
    - {value: bucket}
    - {value: package_folder}
    - {value: cmle_folder}
    - {value: scale_tier}
    - {value: python_module}
    - {value: region}
    - {value: runtime_version}
    - {value: cmle_args}
    - {output: output}
